### ISSUE TITLE
BetterDiscord Plugin

### ISSUE THREAD

**Issue by SpicyTakis** [SynapseTech/TimezoneDB#53] opened 2022-06-12 00:35 UTC
The [BetterDiscord] plugin for TimezoneDB

To Do:
- [ ] Add a Powercord plugin under `platforms/betterdiscord`
- [ ] Display locations
  - [ ] Message
  - [ ] User hover cards
  - [ ] Autocomplete
- [ ] Cache timezone data

[BetterDiscord]: https://betterdiscord.app/

**Comment by LizAinslie** [comment] 2022-06-12 00:36
Lol dupe of #54

**Closed** 2022-06-12 00:36 UTC
